export default {
  playButton: "images/play_button.png",
  screenIndex:0,
  entertain: [
    {
      id: "01",
      name: "Wild Republic",
      seasons: "Staffel 1",
      folgen: "8 Episoden",
      gen: "Drama, 2021",
      actorsTitle:"Schauspieler",
      actors: "Ulrich Tukur, Verena Altenberger,\nFranz Hartwig, Emma Drogunova,\nMerlin Rose, Rouven David Israel",
      description: "Jugenddrama trifft auf Wildnis-Abenteuer: In dem MagentaTV Original gerät eine erlebnispädagogische Maßnahme mit jungen Straftätern außer Kontrolle. Eigentlich sollen die Teenager während einer mehrwöchigen Tour durch die Alpen Gemeinschaftssinn, Solidarität und Rücksicht erlernen – doch dann wird ihr Betreuer tot aufgefunden. Scheinbar weiß niemand, was ihm zugestoßen ist. Die Gruppe gerät in Panik und steht vor einem Dilemma: Die Behörden rufen und selbst in Verdacht geraten? Oder fliehen und das Schicksal in die eigene Hand nehmen? Die Jugendlichen flüchten in die Berge und entdecken eine riesige Höhle, die sie als Versteck nutzen. Im Kampf gegen Naturgewalten und eigene Aggressionen bilden sie eine Gemeinschaft nach eigenen Regeln und wagen den Neustart: die Wild Republic. Die Serie stammt aus der Feder von Arne Nolting und Jan Martin Scharf („Club der roten Bänder“, „Weinberg“) sowie von Klaus Wolfertstetter („Die Klasse“, „Alarm für Cobra 11“).",
      storer: "",
      background: "images/movie_wild_republic.jpg",
      videoURL: "videos/tab_ino_wild_republic.mp4",
    },
    {
      id: "02",
      name: "Lokalrunde",
      seasons: "Staffel 1",
      folgen: "5 Episoden",
      gen: "Kochshow, 2021",
      actorsTitle:"Schauspieler",
      actors: "Antoine Monot",
      description: "Seit Ende der 90er wirkte Antoine Monot in über 80 Kino- und TV-Produktionen mit. Die Figur des Tech-Nick machte ihn 2013 zur Werbe-Ikone, und seit 2014 ist er in „Ein Fall für zwei“ zu sehen. In „Lokalrunde“ geht Monot auf kulinarische Entdeckungstour. In jeder Folge trifft er einen Prominenten, der ihm seine Heimat näherbringt und ihm eine Koch-Aufgabe stellt: Monot muss am Ende ein klassisches lokales Gericht zubereiten. Auf der Suche nach den perfekten Zutaten und Zubereitungstipps besucht er Märkte und trifft sich mit Herstellern aus der Region.",
      storer: "",
      background: "images/movie_lokalrunde.jpg",
      videoURL: "videos/tab_ino_lokalrunde.mp4",
    },
    {
      id: "03",
      name: "Roadkill",
      seasons: "Staffel 1",
      folgen: "4 Episoden",
      gen: "Drama, Polit-Thriller, 2021",
      actorsTitle:"Schauspieler",
      actors: "Hugh Laurie, Helen McCrory,\nIain de Caestecker, Sarah Greene,\nOlivia Vinall",
      description: "Peter Laurence (Hugh Laurie) ist ein politischer Außenseiter, der bei der Bevölkerung sehr beliebt ist. Nach einer erfolgreichen Verleumdungsklage gegen eine Journalistin (Sarah Greene), die Korruptionsvorwürfe gegen ihn erhoben hatte, verspürt er eine Menge Rückenwind. Aber Peter hat zahlreiche Leichen im Keller und schon bald entdeckt er eine weitere – eine uneheliche Tochter, die eine Gefängnisstrafe verbüßt. Ein Geheimnis, das ihn in den Ruin treiben könnte. Und eines, das seiner Premierministerin (Helen McCrory) offenbar nicht verborgen geblieben ist.\n\nDoch Peter scheut keine Risiken. Auch als seine Karriere auf Messers Schneide steht, macht er unerschrocken weiter mit seiner eigenen, kontroversen Form des auf gesundem Menschenverstand beruhenden Libertarismus. Je weiter er sich auf politischer Ebene hervorwagt, desto größer werden seine Probleme. Seine Tochter (Millie Brady) deckt seine Untreue in der Ehe auf und seine Familie droht zusammenzubrechen. Doch dank seines Charmes und Charismas kann er alle Wogen glätten. Vielleicht hat Peter jedoch die Konsequenzen seines Handelns zu lange ignoriert. Denn die Journalistin, die er vor Gericht gedemütigt hat, ist bereits im Einsatz, und möglicherweise wird er sich dieses Mal nicht mehr herausreden können.",
      storer: "",
      background: "images/movie_roadkill.jpg",
      videoURL: "videos/tab_ino_roadkill.mp4",
    },
    {
      id: "04",
      name: "Romulus",
      seasons: "Staffel 1",
      folgen: "10 Episoden",
      gen: "Drama",
      actorsTitle:"Schauspieler",
      actors: "Andrea Arcangeii, Francesco di Napoli,\nMarianna Fontana, Yorgo Voyagis,\nGiovanni Buselli",
      description: "Im achten Jahrhundert vor Christus ist das Leben in Latium rau und primitiv. Als Dürren die Nöte der Menschen verschärfen, befragt König Numitor das Orakel. Dessen Urteil ist hart: Der Regent muss ins Exil und die Krone an seine Zwillingsenkel Enitos und Yemos abtreten. Doch Numitors Bruder Amulius beschließt, die Prinzen aus dem Weg zu räumen und den Thron selbst zu besteigen. Sein Plan geht nicht ganz auf: Yemos kann in die Wälder fliehen. Dort stößt er auf die Anhänger Ruminas. Sie werden von einer Kriegerin angeführt, die ihnen ihren Traum von Ruma näherbringt – einer Stadt, die jeder Macht trotzt und auch Verbannte willkommen heißt. Auf der Grundlage dieser Idee werden sie die Welt verändern.\n\nDas Historiendrama von den Produzenten von „Gomorrha“ ist eine akribische Rekonstruktion des Gründungsmythos Roms. Neben der lateinischen Originalversion sorgen glaubwürdige Figuren und aufwendige Settings für ein hohes Maß an Authentizität.",
      storer: "",
      background: "images/movie_romulus.jpg",
      videoURL: "videos/tab_ino_romulus.mp4",
    },
    {
      id: "05",
      name: "The Pembrokeshire Murders",
      seasons: "Staffel 1",
      folgen: "3 Episoden",
      gen: "Krimi, 2021",
      actorsTitle:"Schauspieler",
      actors: "Luke Evans, Keith Allen,\nAlexandria Riley, David Fynn,\nCharles Dale",
      description: "Das Krimi-Drama ist eine Adaption des True-Crime-Buches „Catching the Bullseye Killer“ von Steve Wilkins und dem Journalisten Jonathan Hill. Darin geht es um zwei ungelöste Doppelmorde aus den 80er Jahren, die einen Schatten auf die Arbeit der Polizei von Dyfed Powys werfen. Im Jahr 2006 beschließt der neu beförderte Detective Superintendent Steve Wilkins, gespielt von Luke Evans („Fast & Furious 6–8“, „Dracula Untold“, „The Alienist – Die Einkreisung“), beide Fälle wieder aufzunehmen. Mit bahnbrechenden forensischen Methoden finden er und sein Team DNA und Fasern, die die Morde unter Umständen mit einer Reihe von Einbrüchen in den 80er und 90er Jahren in Verbindung bringen. Der Täter dieser Einbrüche steht kurz vor dem Ende seiner Haftstrafe, und wenn Steve Recht hat, ist er ein Serienmörder. Können Steve und sein Team genügend Beweise finden, um ihren Verdächtigen anzuklagen, bevor er entlassen wird und möglicherweise erneut tötet?",
      storer: "",
      background: "images/movie_the_pembrokeshire_murders.jpg",
      videoURL: "videos/tab_ino_the_pembrokeshire_murders.mp4",
    },
    {
      id: "06",
      name: "Bestbesetzung",
      seasons: "Staffel 1",
      folgen: "8 Episoden",
      gen: "(Talk-) Show, 2019",
      actorsTitle:"Schauspieler",
      actors: "Johannes B. Kerner",
      description: "In dem MagentaTV Original interviewt Johannes B. Kerner in jeder Episode einen nationalen oder internationalen Star aus den Bereichen Wirtschaft, Politik, Sport, Entertainment und Lifestyle sowie Medien und Gesellschaft. Bei den Gästen handelt es sich um Prominente mit großer Bekanntheit und aktueller Relevanz, die sonst nicht oder nur selten im deutschen Fernsehen zu sehen sind. Nicht nur die Gesprächspartner sind hochkarätig, auch Johannes B. Kerner zählt zu den bekanntesten Moderatoren des Landes. Er wurde mit zahlreichen Preisen wie dem Bambi, der Goldenen Kamera und dem Deutschen Fernsehpreis ausgezeichnet und erhielt 2006 das Bundesverdienstkreuz für sein soziales Engagement. In dem neuen Talkformat unterhält er sich mit seinen Gästen über deren biographischen Werdegang, Persönliches und über das aktuelle Zeitgeschehen. Die Zuschauer können sich auf echte Emotionen, ungeschönte Wahrheiten und spontanen Humor freuen.",
      storer: "",
      background: "images/movie_bestbesetzung.jpg",
      videoURL: "videos/tab_ino_bestbesetzung.mp4",
    },
    {
      id: "07",
      name: "Spy City",
      seasons: "Staffel 1",
      folgen: "6 Episoden",
      gen: "Thriller, 2020",
      actorsTitle:"Schauspieler",
      actors: "Dominic Cooper, Romane Portai,\nJohanna Wokalek, Leonie Benesch",
      description: "Berlin im Jahre 1961. Noch gibt es keine Mauer. Vier Besatzungsmächte lenken das Schicksal der Stadt. Die Stadt wimmelt nur so von Spionen, Verrätern und Doppelagenten des KGB, der CIA und des MI6. In der angespannten Lage muss der britische Spion FieldingScott den Verräter in den eigenen Reihen finden. Eine brisante Mission in einer Stadt, die zum vermeintlich gefährlichsten Ort der Welt geworden ist. Scott erschwert sich seinen eigenen Auftrag, indem er sich in seine französische Amtskollegin verliebt, die zu allem Überfluss in das Zentrum der Ermittlungen rückt.",
      storer: "",
      background: "images/movie_spy_city.jpg",
      videoURL: "videos/tab_ino_spy_city.mp4",
    },
    {
      id: "08",
      name: "Meine geniale Freundin",
      seasons: "Staffel 2",
      folgen: "8 Folgen",
      gen: "Drama, 2020",
      actorsTitle:"Schauspieler",
      actors: "Margherita Mazzucco, Gaia Girace,\nFrancesco Serpico, Giovanni Amura",
      description: "Die beiden Protagonistinnen Lila und Elena sind mittlerweile 16 Jahre alt und haben das Gefühl, lebenstechnisch in einer Sackgasse festzustecken. Lila hat gerade geheiratet, gerät aber in eine Identitätskrise, nachdem sie den Nachnamen ihres Ehemannes annehmen musste. Als sie mit blauen Flecken aus den Flitterwochen zurückkehrt, beginnt sie ihre Entscheidung zu bereuen. In Lila entflammt der Wunsch nach Rache – und nach Freiheit. Elena merkt beim Hochzeitsempfang ihrer besten Freundin, dass sie weder in ihrem Viertel noch außerhalb desselben glücklich ist, und versucht, sich mithilfe von Bildung ihren Weg zu bahnen. Im Gymnasium trifft sie auf den alten Jugendfreund Nino Sarratore und ist von dessen Charisma erneut verzaubert. Doch damit ist sie nicht die Einzige.\n\nAuch in der zweiten Staffel, die auf dem zweiten Band des erfolgreichen Romanzyklus von Elena Ferrante basiert, überzeugen die beiden Hauptdarstellerinnen Gaia Girace und Margherita Mazzucco vor allem durch die spielerische Leichtigkeit, mit der sie den Zuschauern Einblicke in die komplexe Gefühlswelt der Protagonistinnen gewähren. Mit großer Sensibilität verfolgt Regisseur Saverio Costanzo Lila und Elena bei ihren Bemühungen, sich gegen männliches Machtbewusstsein zu behaupten: Während Elena das Leben in Kunst verwandelt und schließlich autobiografische Romane schreibt, verschreibt sich Lila dem Leben selbst – gegen alle Widerstände.",
      storer: "",
      background: "images/movie_meine_geniale_freundin_staffel_2.jpg",
      videoURL: "videos/tab_ino_meine_geniale_freundin_staffel_2.mp4",
    },
    {
      id: "09",
      name: "Condor",
      seasons: "Staffel 2",
      folgen: "tbd Folgen",
      gen: "Action, 2020",
      actorsTitle:"Schauspieler",
      actors: "Max Irons, William Hurt,\nMira Sorvino, Leem Lubany",
      description: "Er arbeitet nicht bei irgendeinem Geheimdienst, sondern bei einem der wichtigsten der USA: bei der CIA. Joe Turner, im Filmklassiker Die drei Tage des Condor einst verkörpert von Robert Redford, ist die Hauptfigur dieser hochspannenden Politthriller-Serie. Mit einer kurzen Zigarettenpause fing alles an: Sie änderte Turners Leben von einer Sekunde auf die andere. Während er mit einer Kollegin vor der Tür stand, fiel das restliche Team einem brutalen Anschlag zum Opfer. Niemand überlebte – außer Turner, der es sich zur Aufgabe machte, die Hintermänner des Attentats aufzuspüren und zur Rechenschaft zu ziehen.\n\nNun kehrt Turner in zehn weiteren Folgen zurück. Er versucht, sein früheres Leben hinter sich zu lassen, doch die Ereignisse von damals verfolgen ihn noch immer. In Budapest wird er von einem russischen Agenten angesprochen. Der bietet Turner an, ihm bei der Suche nach dem Drahtzieher des Anschlags zu helfen – im Gegenzug erhofft er sich politisches Asyl in den USA. Schon bald wird Turner klar: Seiner eigenen Vergangenheit kann niemand entrinnen, selbst er nicht. Also unterstützt er den russischen Überläufer und gerät mitten hinein in das nächste tödliche Spiel.",
      storer: "",
      background: "images/movie_condor_staffel_2.jpg",
      videoURL: "videos/tab_ino_condor_staffel_2.mp4",
    },
    {
      id: "10",
      name: "Tenet",
      seasons: "Action, 2020",
      folgen: "",
      gen: "",
      actorsTitle:"Schauspieler",
      actors: "Robert Pattinson, Aaron Taylor-Johnson,\nElizabeth Debicki, Himesh Patel,\nClémence Poésy\n\n© 2020 Warner Bros. Entertainment Inc.",
      description: "Für den zielstrebigen Rookie eröffnet sich nach einer lebensgefährlichen Mission eine neue Tür. Im Krankenhausbett erwachend, wird ihm bescheinigt, einen Test bestanden zu haben. Er ist nun Teil des „Jenseits“.\n\nDie Welt, die ihn jetzt erwartet, ist nicht weniger gefährlich. Ganz im Gegenteil: Zeitparadoxien, lebensgefährliche Verfolgungsjagden und Aufträge in luftiger Höhe erwarten ihn. Als Teil eines Teams soll er an einer streng geheimen Mission arbeiten, über dessen wahren Hintergründe nur wenige Bescheid wissen. Angeblich geht es darum, den Dritten Weltkrieg zu verhindern, hinter dem sich jedoch nicht der nukleare Holocaust verbirgt, sondern ein weitaus schlimmeres Schicksal für die Menschheit.",
      storer: "ZUM MIETEN & KAUFEN BEI MAGENTA TV",
      background: "images/movie_tenet.jpg",
      videoURL: "videos/tab_ino_tenet.mp4",
    },
  ],
};
