export default {
  playButton: "images/play_button.png",
  screenIndex:3,
  entertain: [
    {
      id: "01",
      name: "Drachenreiter",
      seasons: "Film",
      folgen: "",
      gen: "",
      actorsTitle:"",
      actors: "© Inhaberin der ausschließlichen Nutzungsrechte ist die Constantin Film Verleih GmbH",
      description: "Der junge Silberdrache Lung hat es satt, sich ständig im Dschungel verstecken zu müssen. Er möchte der älteren Generation unbedingt beweisen, dass er ein richtiger Drache ist. Als die Menschen kurz davorstehen, auch noch den letzten Rückzugsort seiner Familie zu zerstören, begibt sich Lung zusammen mit Koboldmädchen Schwefelfell heimlich auf eine abenteuerliche Reise. Er möchte den „Saum des Himmels“ finden, den geheimnisvollen Zufluchtsort der Drachen.\n\nAuf ihrer Suche begegnen Lung und Schwefelfell Ben, einem Waisenjungen und Streuner, der sich als Drachenreiter ausgibt. Während sich Ben und Lung schnell anfreunden, wird Schwefelfell zunehmend misstrauischer und versucht, den Waisenjungen bei jeder Gelegenheit loszuwerden. Doch das ungleiche Trio muss lernen, an einem Strang zu ziehen, denn sie werden von Nesselbrand verfolgt. Das bösartige, drachenfressende Monster hat es darauf abgesehen, alle Drachen der Erde aufzuspüren und zu vernichten…",
      storer: "ZUM MIETEN & KAUFEN BEI MAGENTA TV",
      background: "images/movie_drachenreiter.jpg",
      videoURL: "videos/tab_ino_drachenreiter.mp4",
    },
    {
      id: "02",
      name: "Die Abenteuer von Tim und Struppi – Das Geheimnis der Einhorn",
      seasons: "Film",
      folgen: "",
      gen: "",
      actorsTitle:"",
      actors: "© 2011 Columbia Pictures Industries, Inc., DW Studios L.L.C. and Hemisphere - Culver Picture Partners I, LLC. All Rights Reserved.",
      description: "Auf einem Trödelmarkt ersteht Reporter Tim ein Modell der versunkenen „Einhorn“. Bald schon ist allerlei Gesindel hinter dem Schiffchen her. Tim hat kein Interesse an einem Verkauf und wird schließlich hinterrücks niedergeschlagen. Im Bauch eines echten Schiffes kommt er wieder zu sich. Hier trifft er auf den dauerbeschwipsten Kapitän Haddock, der nach dem Schatz eines Vorfahren sucht. Tim und sein gewitzter Foxterrier Struppi schließen sich dem Abenteuer an und treffen schon bald wieder auf alte Bekannte…",
      storer: "",
      background: "images/movie_tim_und_struppi.jpg",
      videoURL: "videos/tab_ino_tim_und_struppi.mp4",
    },
    {
      id: "03",
      name: "Shrek 4 -Für immer Shrek",
      seasons: "Film",
      folgen: "",
      gen: "",
      actorsTitle:"",
      actors: "SHREK FOREVER AFTER ™ & © 2021 DreamWorks Animation LLC. All Rights Reserved.",
      description: "Shrek hat sich widerwillig in das domestizierte Leben eines Familienvaters gefügt, in dem die größte Aufregung noch das Unterzeichnen von Mistgabeln ist. Shrek sehnt sich nach den aufregenden Tagen von einst und lässt sich von Rumpelstilzchen zu einem folgenschweren Pakt überreden, dessen Tragweite Shrek zu spät erkennt. Denn auf einmal ist Rumpelstilzchen König von weit, weit weg.",
      storer: "AUF ABRUF BEI\nMAGENTA TV",
      background: "images/movie_shrek.jpg",
      videoURL: "videos/tab_ino_shrek.mp4",
    },
    {
      id: "04",
      name: "Paw Patrol",
      seasons: "Serie",
      folgen: "",
      gen: "",
      actorsTitle:"",
      actors: "© 2020 Viacom International Inc. Alle rechte vorbehalten.",
      description: "Paw Patrol ist eine Vorschulserie mit sechs heldenhaften Hunden in der Hauptrolle: Chase, Marshall, Rocky, Zuma, Rubble und Skye. Sie werden von dem 10-jährigen Technikliebhaber Ryder angeführt.",
      storer: "AUF ABRUF BEI\nMAGENTA TV",
      background: "images/movie_paw_patrol.jpg",
      videoURL: "videos/tab_ino_paw_patrol.mp4",
    },
    {
      id: "05",
      name: "Power Players",
      seasons: "Serie",
      folgen: "",
      gen: "",
      actorsTitle:"",
      actors: "© 2019 - Zagtoon – Method Animation – France Televisions – Planeta Junior – WDR – WDR mediagroup",
      description: "Der neunjährige Axel wohnt bei seinem Onkel André, einem Spielzeugerfinder. Eines Tages entdeckt er dessen geheimes Labor und findet dort die unglaublichen Powerbänder: Mit ihrer Hilfe verwandelt Axel sich in ein lebendiges Action-Spielzeug und hat plötzlich Superkräfte zur Verfügung.",
      storer: "AUF ABRUF BEI\nMAGENTA TV",
      background: "images/movie_power_players.jpg",
      videoURL: "videos/tab_ino_power_players.mp4",
    },
    
  ],
};
